In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense

In [2]:
reviews = [
    'nice food',
    'amazing restaurant',
    'too good',
    'just loved it!',
    'will go again',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvement'
]

In [3]:
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
vocab_size = 30  # total number of unique words we assume
encoded_reviews = [one_hot(sentence, vocab_size) for sentence in reviews]
print("Encoded reviews (word -> number):")
print(encoded_reviews)

Encoded reviews (word -> number):
[[29, 5], [13, 23], [16, 18], [5, 17, 2], [14, 21, 5], [12, 5], [6, 21, 16], [1, 9], [1, 27], [24, 9]]


In [5]:
max_length = 4  
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print("\nPadded reviews:")
print(padded_reviews)


Padded reviews:
[[29  5  0  0]
 [13 23  0  0]
 [16 18  0  0]
 [ 5 17  2  0]
 [14 21  5  0]
 [12  5  0  0]
 [ 6 21 16  0]
 [ 1  9  0  0]
 [ 1 27  0  0]
 [24  9  0  0]]


In [6]:
embedding_vector_size = 5

In [7]:
model = Sequential()

In [8]:
model.add(Embedding(vocab_size, embedding_vector_size, input_length=max_length, name="embedding"))

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
model.add(Flatten())

In [10]:
model.add(Dense(1, activation='sigmoid'))

In [11]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [12]:
model.fit(padded_reviews, sentiment, epochs=50, verbose=0)


In [13]:
loss, accuracy = model.evaluate(padded_reviews, sentiment)
print("\nAccuracy:", accuracy)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 1.0000 - loss: 0.6241

Accuracy: 1.0


In [14]:
weights = model.get_layer('embedding').get_weights()[0]
print("\nEmbedding matrix shape:", weights.shape)


Embedding matrix shape: (30, 5)


In [15]:
print("\nVector for word index 13:", weights[13])
print("Vector for word index 4:", weights[4])
print("Vector for word index 16:", weights[16])


Vector for word index 13: [-0.09495953  0.00410892 -0.04061373 -0.02253535 -0.03112851]
Vector for word index 4: [ 0.04784722 -0.03065668  0.03450621  0.03629811  0.03759041]
Vector for word index 16: [-0.09223876  0.06452952 -0.05208256 -0.06117107 -0.07344714]
